# Copyright Istio Authors
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

##################################################################################################
# This file defines the services, service accounts, and deployments for the Bookinfo sample.
#
# To apply all 4 Bookinfo services, their corresponding service accounts, and deployments:
#
#   kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml
#
# Alternatively, you can deploy any resource separately:
#
#   kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml -l service=reviews # reviews Service
#   kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml -l account=reviews # reviews ServiceAccount
#   kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml -l app=reviews,version=v3 # reviews-v3 Deployment
##################################################################################################

##################################################################################################
# Presenter service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: presenter
  labels:
    app: presenter
    service: presenter
spec:
  type: LoadBalancer
  ports: 
    - port: 1880
      protocol: TCP
  selector:
    app: presenter
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crawlerpresenter-presenter
  labels:
    account: presenter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: presenter-v1
  labels:
    app: presenter
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: presenter
      version: v1
  template:
    metadata:
      labels:
        app: presenter
        version: v1
    spec:
      serviceAccountName: crawlerpresenter-presenter
      containers:
      - name: presenter
        image: salzg/kuberun:presenter-v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1880
          protocol: TCP
        
---
##################################################################################################
# Crawler service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: crawler
  labels:
    app: crawler
    service: crawler
spec:
  type: LoadBalancer
  ports:
  - port: 1885
    targetPort: 1885
    protocol: TCP
  selector:
    app: crawler
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crawlerpresenter-crawler
  labels:
    account: crawler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler-v1
  labels:
    app: crawler
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler
      version: v1
  template:
    metadata:
      labels:
        app: crawler
        version: v1
    spec:
      serviceAccountName: crawlerpresenter-crawler
      containers:
      - name: crawler
        image: salzg/kuberun:crawler-v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1885
          protocol: TCP
