##################################################################################################
# This file defines the services, service accounts, and deployments for the Bookinfo sample.
#
# To apply all 4 Bookinfo services, their corresponding service accounts, and deployments:
#
#   kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml
#
# Alternatively, you can deploy any resource separately:
#
#   kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml -l service=reviews # reviews Service
#   kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml -l account=reviews # reviews ServiceAccount
#   kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml -l app=reviews,version=v3 # reviews-v3 Deployment
##################################################################################################

##################################################################################################
# Opc shim
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: opcuashim
  labels:
    app: opcuashim
    service: opcuashim
spec:
  ports: 
    - port: 1880
      name: http
  selector:
    app: opcuashim
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opc-opcuashim
  labels:
    account: opcuashim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opcuashim-v1
  labels:
    app: opcuashim
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opcuashim
      version: v1
  template:
    metadata:
      labels:
        app: opcuashim
        version: v1
    spec:
      serviceAccountName: opc-opcuashim
      containers:
      - name: opcuashim
        image: salzg/opc-ua-shim:0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1880
          protocol: TCP
---
